set_property SRC_FILE_INFO {cfile:C:/Users/anags/OneDrive/Desktop/project_1/project_1.srcs/constrs_1/new/serie.xdc rfile:../../../project_1.srcs/constrs_1/new/serie.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    W5   [get_ports sys_clock]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   U18   [get_ports reset]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   A18   [get_ports TX]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   B18   [get_ports RX]
