webtalk_init -webtalk_dir C:/Users/anags/OneDrive/Desktop/UNI/cuatri 2/Sistemas Digitales Avanzados/Practicas/p3/FPGA/FPGA/FPGA.sim/sim_1/behav/xsim/xsim.dir/top_osci_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 14 13:42:21 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f4f5a224-5196-4320-960f-9f7e49c03387" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5c88acd502c9430ea315698e6a20f74f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1010 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6356_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3186961546 -regid "" -xml C:/Users/anags/OneDrive/Desktop/UNI/cuatri 2/Sistemas Digitales Avanzados/Practicas/p3/FPGA/FPGA/FPGA.sim/sim_1/behav/xsim/xsim.dir/top_osci_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/anags/OneDrive/Desktop/UNI/cuatri 2/Sistemas Digitales Avanzados/Practicas/p3/FPGA/FPGA/FPGA.sim/sim_1/behav/xsim/xsim.dir/top_osci_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/anags/OneDrive/Desktop/UNI/cuatri 2/Sistemas Digitales Avanzados/Practicas/p3/FPGA/FPGA/FPGA.sim/sim_1/behav/xsim/xsim.dir/top_osci_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
